services:
  app:
    build: .
    container_name: controlecred_app
    user: "${UID}:${GID}"
    ports:
      - "8087:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: controlecred_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: controlecred
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: controlecred
      MYSQL_PASSWORD: controlecred
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: controlecred_phpmyadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
